# Alacritty config file
# by ngtm/naut

# general (The root level of the configuration file)
# # import = [string] (import anoter toml file,...)
# # shell = "powershell"
# # working_directory = "C:/User/Rover"
live_config_reload = true
# # ipc_socket

[env]

# All key-value pairs in the [env] section will be added as environment variables 
# for any process spawned by Alacritty, including its shell. 
# Some entries may override variables set by alacritty itself

[window]

# Window dimensions (lines and columns)
dimensions = { columns = 0, lines = 0 }

# Window startup position (in pixels)
position = { x = 1000, y = 2 }

# Blank space added around the window in pixels (scaled by DPI)
padding = { x = 6, y = 6 }

# Spread additional padding evenly around the terminal content
dynamic_padding = false

# Window decorations (Full/None)
decorations = "Full"

# Background opacity (0.0-1.0)
opacity = 0.95

# Request compositor to blur content behind (macOS/KDE Wayland)
blur = true

# Startup mode ( "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen" )
startup_mode = "Windowed"

# Window title
title = "Alacritty"

# Allow terminal applications to change Alacritty's window title
dynamic_title = false

# Window class (Linux/BSD only)
# # class = { instance = "Alacritty", general = "Alacritty" }

# Override the variant of the System decorations ( "Dark" | "Light" | "None" )
decorations_theme_variant = "Dark"

# Prefer resizing window by discrete steps equal to cell dimensions
resize_increments = false

# Make Option key behave as Alt (macOS only)
# # option_as_alt = "OnlyLeft" | "OnlyRight" | "Both" | "None"

[scrolling]

# Maximum number of lines in the scrollback buffer
history = 10000

# Number of line scrolled for every input scroll increment
multiplier = 3

[font]

# Font { family = "<string>", style = "<string>" }
# If the family is not specified, it will fall back to the value specified for the normal font
normal = { family = "JetbrainsMono NF SemiBold", style = "Regular" }
bold = { family = "JetbrainsMono NF SemiBold", style = "Regular" }
italic = { family = "JetbrainsMono NF SemiBold" }
bold_italic = { family = "JetbrainsMono NF SemiBold" }

# Font size in points
size = 10

# Offset is the extra space around each character. y can be thought of as 
# modifying the line spacing, and x as modifying the letter spacing
offset = { x = 1, y = 0 }

# Glyph offset determines the locations of the glyphs within their cells with
# the default being at the bottom. Increasing x moves the glyph to the right,
# increasing y moves the glyph upward
glyph_offset = { x = 0, y = 0 }

# When true, Alacritty will use a custom built-in font for box drawing
# characters (Unicode points U+2500 - U+259F) and powerline symbols (Unicode
# points U+E0B0 - U+E0B3).
builtin_box_drawing = true

[colors]
    
    [colors.primary]
    foreground = "#ebdbb2"
    background = "#1d2021"
    dim_foreground = "None"
    bright_foreground = "None"

    
    [colors.normal]
    black = "#141617"
    red = "#ea6962"
    green = "#a9b665"
    yellow = "#d8a657"
    blue = "#7daea3"
    magenta = "#ea6962"
    cyan = "#89b482"
    white = "#ebdbb2"

[bell]


[selection]

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = "None"
# # blinking_interval = 750
# # blinking_timeout = 0
unfocused_hollow = true
thickness = 0.1
